import { For, Show, createMemo } from 'solid-js'
import { ambientWeek, refetchAmbientWeek } from '../../data/relay'
import styles from './AmbientWeek.module.css'

// AmbientWeek — the real, buildable "bigger sample size" for the AMBIENT
// panel's top section. AmbientPanel's star rating / editorial claim /
// sport of the week / quality alerts are entirely server-generated by
// ONE real per-date endpoint (/analytics/newspaper/{date}) -- unlike
// DramaLeaderboard/HallOfSurprises, there's no server-side limit param
// to widen. The only genuine way to give this content a bigger sample
// is to call that same real endpoint across a real date range
// (src/data/relay.js's ambientWeek resource) and let a viewer see more
// than tonight alone.
//
// Confirmed real and safe to build on via a direct multi-date probe,
// 2026-08-03 (outbox/ambient-multiday-probe-2026-08-03T18-06-10-315Z.txt):
// 10/10 real recent dates resolved, 10/10 distinct real editorial
// claims, 7/10 distinct star scores -- genuine day-to-day variation,
// not a repeated cached value.
//
// A real, currently-live bug was found and fixed in the same pass
// (AmbientPanel's SportOfWeekBanner rendered the raw sport_of_week
// object as "[object Object]" instead of its real `summary` field) --
// not repeated here.
export function AmbientWeek() {
  const days = createMemo(() => {
    const data = ambientWeek.error ? undefined : ambientWeek()
    return data ?? []
  })

  const okDays = createMemo(() => days().filter(d => d.ok))

  const best = createMemo(() => {
    const list = okDays().filter(d => d.data?.night_stars?.starScore != null)
    if (!list.length) return null
    return list.reduce((a, b) => (b.data.night_stars.starScore > a.data.night_stars.starScore ? b : a))
  })

  return (
    <div class={styles.root}>
      <header class={styles.header}>
        <span class={styles.label}>Ambient Week</span>
        <button class={styles.refreshBtn} onClick={refetchAmbientWeek} aria-label="refresh">↻</button>
      </header>
      <p class={styles.note}>
        The same real editorial recap AMBIENT shows for tonight, across the last {days().length || 10} real
        days — a bigger sample than any single night can give.
      </p>

      <Show when={ambientWeek.error}>
        <p class={styles.error}>{String(ambientWeek.error)}</p>
      </Show>

      <Show when={!ambientWeek.error}>
        <Show when={days().length} fallback={<p class={styles.loading}>Loading…</p>}>
          <p class={styles.summary}>
            {okDays().length}/{days().length} real days resolved
            <Show when={best()}>
              {' '}· best night: {best().date} (drama intensity {best().data.night_stars.starScore.toFixed(1)})
            </Show>
          </p>
          <ul class={styles.rows}>
            <For each={days()}>
              {d => (
                <li class={styles.row}>
                  <span class={styles.date}>{d.date}</span>
                  <Show when={d.ok} fallback={<span class={styles.unavailable}>unavailable</span>}>
                    <Show when={d.data.night_stars} fallback={<span class={styles.noStars}>no rating</span>}>
                      <span class={styles.stars} title={`drama intensity ${d.data.night_stars.starScore}`}>
                        {'★'.repeat(Math.min(5, d.data.night_stars.stars))}{'☆'.repeat(Math.max(0, 5 - d.data.night_stars.stars))}
                      </span>
                    </Show>
                    <span class={styles.claim}>{d.data.truth_is?.headline ?? '—'}</span>
                  </Show>
                </li>
              )}
            </For>
          </ul>
        </Show>
      </Show>
    </div>
  )
}
