import { For, Show, createSignal, createMemo, createEffect, onCleanup } from 'solid-js'
import { deskStore } from '../../data/relay'
import styles from './DramaSoundscape.module.css'

// DramaSoundscape — the first non-visual surface in this playground.
// Explicitly NOT ambient/atmospheric (the original pitch was closer to
// that -- rising tones, sustained pads). Redirected toward comedic,
// recognizable cartoon SFX -- boings, slide-whistle glides, trombone
// wah-wahs, xylophone runs, a game-show "ding!" -- because that's
// FIELD's own established register (WARM/UPLIFTING/CHEEKY/WRY) and
// because "fun" is a real, checkable creative target in a way
// "ethereal" mostly isn't.
//
// EVERY SOUND IS SYNTHESIZED, NONE SAMPLED -- no audio files, no
// licensed or franchise material. This deliberately evokes a generic
// cartoon-SFX VOCABULARY (the slide whistle, the boing, the wah-wah
// trombone are decades-old, non-proprietary sound tropes) without
// naming or referencing any specific franchise anywhere in this file
// or the UI.
//
// FOUND 2026-07-31, user actually listening: "Sounds 8-bit but not in
// a good way." First fix (Tone.MonoSynth + a lowpass filter on the
// two raw sawtooth/square voices) addressed the literal harshness but
// was still hand-tuned raw oscillators underneath. Replaced the whole
// engine: webaudio-tinysynth (g200kg/webaudio-tinysynth, Apache-2.0,
// zero dependencies) is a real General MIDI-mapped FM synthesizer --
// "All timbres are generated by the combinations of Oscillator and
// dynamically generated BufferSource algorithmically without any PCM
// samples" (its own README, confirmed directly, not assumed) --
// `quality:1` mode specifically, since `quality:0` is documented as
// "chiptune like," the exact thing being moved away from. Real GM
// instrument programs, confirmed against the library's own source
// (its timbre name table, not the general MIDI spec sheet from
// memory): Trombone=57, Xylophone=13, Tubular Bells=14, Whistle=78 --
// the last one a genuinely better thematic match for the "boing" cue
// than a generic sine ever was.
//
// Tone.js loads from a CDN ESM import at runtime, not an npm
// dependency -- package.json isn't reachable through the mobile-chat
// session's write path that first built this file (confirmed: not in
// its MCP read/write allowlist). This sandbox can't fetch the CDN URL
// directly either (host_not_allowed -- its own egress allowlist, not
// a real rejection), so the actual proof this loads is the render
// harness running in a real headless browser via CI, same as every
// other verification this session has relied on.
//
// SIX TRIGGERS, ALL FROM FIELDS ALREADY CONFIRMED REAL TODAY -- no
// invented event types:
//   lead change        -- home_score/away_score sign flip
//   comeback            -- deficit shrinking fast (reuses round 2's
//                          comeback_magnitude shape, simplified to a
//                          live per-tick delta rather than a final
//                          game-level max)
//   blowout developing  -- |diff| crossing a threshold, growing
//   new hottest game     -- drama_peak leader across the slate changing
//                          (same ranking TonightsPick already computes)
//   extra frames         -- went_to_ot flipping true (real field;
//                          deliberately NOT a separate inning fetch --
//                          duplicating LiveWpTicker's statsapi pipeline
//                          into a second component would be exactly
//                          the disconnected-systems pattern flagged
//                          more than once elsewhere in this project)
//   dramatic final        -- finalized_at newly set + went_to_ot true,
//                          i.e. the game that just ended went the
//                          distance
//
// NEVER AUTOPLAYS. Browsers block audio without a user gesture, and
// it's the right call regardless -- a tap-to-enable gate, off by
// default, with the trigger log visible even before sound is enabled
// so the mapping is inspectable without needing audio on at all.

const CDN_URL = 'https://esm.sh/webaudio-tinysynth@1.1.3'

// Confirmed directly from g200kg/webaudio-tinysynth's own source
// (its GM timbre name table), not the general spec sheet from memory.
const GM = { WHISTLE: 78, TROMBONE: 57, XYLOPHONE: 13, TUBULAR_BELLS: 14 }
// One MIDI channel per cartoon gesture -- each keeps its own program
// and pitch-bend state independently, same one-instrument-per-gag
// reasoning the prior Tone.js version already used.
const CH = { boing: 0, trombone: 1, xylo: 2, bell: 3 }

function gameKey(g) { return g.away + '@' + g.home }

function gameStatus(g) {
  if (g.home_score === null) return 'pre'
  if (g.finalized_at) return 'final'
  return 'live'
}

export function DramaSoundscape() {
  const [enabled, setEnabled] = createSignal(false)
  const [volume, setVolume] = createSignal(0.6) // linear 0-1, webaudio-tinysynth's own scale
  const [loading, setLoading] = createSignal(false)
  const [loadError, setLoadError] = createSignal(null)
  const [log, setLog] = createSignal([]) // [{id, label, icon, t}]
  const [synth, setSynth] = createSignal(null)

  // Previous-tick snapshot per game, to detect real TRANSITIONS rather
  // than re-firing on every unchanged poll.
  let prevByKey = {}
  let prevHottest = null

  function pushLog(label, icon) {
    setLog(l => [{ id: Math.random().toString(36).slice(2), label, icon, t: Date.now() }, ...l].slice(0, 12))
  }

  async function enableSound() {
    setLoading(true)
    setLoadError(null)
    try {
      const mod = await import(/* @vite-ignore */ CDN_URL)
      const WebAudioTinySynth = mod.default ?? mod.WebAudioTinySynth ?? mod
      const s = new WebAudioTinySynth({ quality: 1, useReverb: 0 })
      // getAudioContext() exists specifically so the required
      // user-gesture unlock (this function only ever runs from a
      // click handler) can be made explicit, same role Tone.start()
      // played in the previous engine.
      await s.getAudioContext().resume()
      s.setProgram(CH.boing, GM.WHISTLE)
      s.setProgram(CH.trombone, GM.TROMBONE)
      s.setProgram(CH.xylo, GM.XYLOPHONE)
      s.setProgram(CH.bell, GM.TUBULAR_BELLS)
      // A full octave of bend range specifically for the whistle
      // channel's glide -- the other three channels never bend.
      s.setBendRange(CH.boing, 1200)
      s.setMasterVol(volume())
      setSynth(s)
      setEnabled(true)
    } catch (e) {
      setLoadError(String(e?.message ?? e))
    } finally {
      setLoading(false)
    }
  }

  onCleanup(() => {
    const s = synth()
    if (s) { s.allSoundOff(CH.boing); s.allSoundOff(CH.trombone); s.allSoundOff(CH.xylo); s.allSoundOff(CH.bell); s.getAudioContext()?.close?.() }
  })

  // --- The six cartoon gestures, real GM note numbers (60 = middle C,
  // confirmed in the library's own docs) ---

  function playBoing() {
    // A whistle glide, bent upward in discrete steps -- setBend
    // schedules an instantaneous value at each timestamp (confirmed
    // from source: it's a detune.setValueAtTime call, not a ramp), so
    // several close-together steps approximate a glide rather than
    // one continuous sweep.
    const s = synth(); if (!s) return
    const t = s.getAudioContext().currentTime
    s.noteOn(CH.boing, 60, 100, t)
    s.setBend(CH.boing, 8192, t)
    s.setBend(CH.boing, 11000, t + 0.04)
    s.setBend(CH.boing, 14000, t + 0.08)
    s.setBend(CH.boing, 16383, t + 0.12)
    s.noteOff(CH.boing, 60, t + 0.15)
    s.setBend(CH.boing, 8192, t + 0.16) // reset for the next hit
  }

  function playWahTrombone() {
    // Three descending notes plus a held low note -- the classic
    // disappointment "wah-wah-wah-waaah," a real trombone FM voice
    // this time instead of a raw sawtooth.
    const s = synth(); if (!s) return
    const t = s.getAudioContext().currentTime
    const notes = [55, 53, 50, 48] // G3 F3 D3 C3
    notes.forEach((n, i) => {
      const start = t + i * 0.2
      const dur = i === 3 ? 0.5 : 0.18
      s.noteOn(CH.trombone, n, 100, start)
      s.noteOff(CH.trombone, n, start + dur)
    })
  }

  function playXyloRun() {
    // A fast ascending run of DISCRETE notes -- the "climbing back in"
    // cartoon run, a real xylophone FM voice.
    const s = synth(); if (!s) return
    const t = s.getAudioContext().currentTime
    const notes = [60, 62, 64, 67, 72] // C4 D4 E4 G4 C5
    notes.forEach((n, i) => {
      const start = t + i * 0.07
      s.noteOn(CH.xylo, n, 100, start)
      s.noteOff(CH.xylo, n, start + 0.08)
    })
  }

  function playDing() {
    // A bright bell + a two-note tiny fanfare -- game-show "correct
    // answer," a real tubular-bells FM voice instead of a plain sine.
    const s = synth(); if (!s) return
    const t = s.getAudioContext().currentTime
    s.noteOn(CH.bell, 76, 100, t) // E5
    s.noteOff(CH.bell, 76, t + 0.4)
    s.noteOn(CH.bell, 84, 100, t + 0.12) // C6
    s.noteOff(CH.bell, 84, t + 0.12 + 0.5)
  }

  function playSuspense() {
    // Three low notes, deliberately over-fast for the register (a
    // real suspense sting is slow; playing it too quick is what makes
    // it read as a gag rather than genuinely ominous).
    const s = synth(); if (!s) return
    const t = s.getAudioContext().currentTime
    const notes = [36, 36, 31] // C2 C2 G1
    notes.forEach((n, i) => {
      const start = t + i * 0.18
      s.noteOn(CH.trombone, n, 100, start)
      s.noteOff(CH.trombone, n, start + 0.2)
    })
  }

  function playTaDa() {
    // Ascending major triad + octave, held -- the cartoon "ta-da!"
    const s = synth(); if (!s) return
    const t = s.getAudioContext().currentTime
    const notes = [60, 64, 67, 72] // C4 E4 G4 C5
    notes.forEach((n, i) => {
      const start = t + i * 0.1
      const dur = i === 3 ? 0.6 : 0.15
      s.noteOn(CH.bell, n, 100, start)
      s.noteOff(CH.bell, n, start + dur)
    })
  }

  // --- Real-data transition detection ---

  const games = createMemo(() => [...(deskStore.games?.regular ?? []), ...(deskStore.games?.postseason ?? [])])

  // REAL BUG, FOUND 2026-07-31 (user report: "soundboard doesn't play
  // live"): this was a bare createMemo whose return value nothing ever
  // reads. Confirmed in isolation (node test, solid-js core, no DOM):
  // an unread createMemo runs exactly ONCE at creation and never
  // re-runs on subsequent dependency changes -- memos are lazy/pull-
  // based in Solid, so with zero consumers there is nothing to pull.
  // createEffect is push-based and always re-runs when its tracked
  // dependencies change, which is what a side-effect-only computation
  // (detecting transitions, firing sounds) actually needs.
  createEffect(() => {
    const list = games()
    if (!list.length) return

    // Slate-wide: has the drama_peak leader changed?
    const withPeak = list.filter(g => typeof g.drama_peak === 'number')
    if (withPeak.length) {
      const hottest = [...withPeak].sort((a, b) => b.drama_peak - a.drama_peak)[0]
      const hk = gameKey(hottest)
      if (prevHottest !== null && prevHottest !== hk) {
        pushLog(`${hottest.away} @ ${hottest.home} takes the slate lead`, '🔔')
        if (enabled()) playDing()
      }
      prevHottest = hk
    }

    for (const g of list) {
      const k = gameKey(g)
      const prev = prevByKey[k]
      const status = gameStatus(g)

      if (prev && status === 'live' && prev.status === 'live' &&
          g.home_score !== null && prev.home_score !== null) {
        const prevDiff = prev.home_score - prev.away_score
        const diff = g.home_score - g.away_score

        // Lead change: sign flipped (and it wasn't already 0-0)
        if (prevDiff !== 0 && diff !== 0 && Math.sign(prevDiff) !== Math.sign(diff)) {
          pushLog(`${g.away} @ ${g.home} — lead change`, '🫠')
          if (enabled()) playBoing()
        }

        // Comeback: the trailing margin shrank by 3+ in one tick
        const prevMargin = Math.abs(prevDiff)
        const margin = Math.abs(diff)
        if (prevMargin - margin >= 3 && margin > 0) {
          pushLog(`${g.away} @ ${g.home} — closing fast`, '🎢')
          if (enabled()) playXyloRun()
        }

        // Blowout developing: margin crosses 8+ and is still growing
        if (margin >= 8 && margin > prevMargin) {
          pushLog(`${g.away} @ ${g.home} — getting away from them`, '📉')
          if (enabled()) playWahTrombone()
        }
      }

      // Extra frames just started (went_to_ot flips false -> true)
      if (prev && !prev.went_to_ot && g.went_to_ot) {
        pushLog(`${g.away} @ ${g.home} — extra frames`, '⏰')
        if (enabled()) playSuspense()
      }

      // Just went final, and it went the distance
      if (prev && prev.status !== 'final' && status === 'final' && g.went_to_ot) {
        pushLog(`${g.away} @ ${g.home} — final, the hard way`, '🎉')
        if (enabled()) playTaDa()
      }

      prevByKey[k] = { home_score: g.home_score, away_score: g.away_score, status, went_to_ot: g.went_to_ot }
    }
  })

  return (
    <div class={styles.root}>
      <header class={styles.header}>
        <span class={styles.label}>Drama Soundscape</span>
        <span class={styles.note}>cartoon SFX, not ambient tone — every sound is a real game transition</span>
      </header>

      <Show when={!enabled()}>
        <button class={styles.enableBtn} onClick={enableSound} disabled={loading()}>
          {loading() ? 'loading…' : '🔊 tap to enable sound'}
        </button>
        <Show when={loadError()}>
          <p class={styles.error}>Couldn't load: {loadError()}</p>
        </Show>
      </Show>

      <Show when={enabled()}>
        <div class={styles.controls}>
          <span class={styles.onBadge}>● sound on</span>
          <label class={styles.volLabel}>
            vol
            <input
              type="range" min="0" max="1" step="0.05" value={volume()}
              onInput={e => {
                const v = Number(e.target.value)
                setVolume(v)
                synth()?.setMasterVol(v)
              }}
            />
          </label>
        </div>

        {/* On-demand preview -- waiting for a real lead change to check
            whether a sound design actually works is impractical. Same
            functions the real triggers call, fired directly. This is
            also how the blowout/extra-frames pair (shared trombone
            channel) and new-hottest/dramatic-final pair (shared bell
            channel) -- the two structurally-closest sounds, confirmed
            by a distinctness check across note pattern -- are meant to
            be checked specifically against each other. */}
        <div class={styles.previewRow}>
          <span class={styles.previewLabel}>preview:</span>
          <button class={styles.previewBtn} onClick={playBoing}>🫠 lead change</button>
          <button class={styles.previewBtn} onClick={playXyloRun}>🎢 comeback</button>
          <button class={styles.previewBtn} onClick={playWahTrombone}>📉 blowout</button>
          <button class={styles.previewBtn} onClick={playDing}>🔔 new hottest</button>
          <button class={styles.previewBtn} onClick={playSuspense}>⏰ extra frames</button>
          <button class={styles.previewBtn} onClick={playTaDa}>🎉 dramatic final</button>
        </div>
      </Show>

      <div class={styles.legend}>
        <span>🫠 lead change</span>
        <span>🎢 comeback</span>
        <span>📉 blowout</span>
        <span>🔔 new hottest</span>
        <span>⏰ extra frames</span>
        <span>🎉 dramatic final</span>
      </div>

      <Show when={log().length} fallback={<p class={styles.empty}>Watching for real transitions…</p>}>
        <ul class={styles.logList}>
          <For each={log()}>
            {entry => <li class={styles.logItem}><span>{entry.icon}</span> {entry.label}</li>}
          </For>
        </ul>
      </Show>
    </div>
  )
}
